model:
  arch: rnachat
  model_type: pretrain_vicuna

  # Stage 2
  freeze_rna_encoder: True
  freeze_lp: True
  freeze_llama: False

  llama_model: ""
  prompt: ""

  max_txt_len: 405
  end_sym: "###"
  low_resource: False
  embedding_agg: 1
  peft_ckpt: ''
  stage1_ckpt: ""
  
datasets:
  rna:
    data_type: rna
    build_info:
      train:
        storage: data/train_set

run:
  task: BaseTask
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 5e-5
  min_lr: 5e-6
  warmup_lr: 5e-6
  accum_grad_iters: 4

  weight_decay: 0.005
  max_epoch: 5
  iters_per_epoch: 4200
  batch_size_train: 1
  batch_size_eval: 1
  num_workers: 4
  warmup_steps: 0

  seed: 42
  output_dir: ""

  amp: True
  resume_ckpt_path: null

  printable: False # whether all ranks can print (True) or only rank 0 can print (False)

  evaluate: False 
  train_splits: ["train"]
  valid_splits: ["valid"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
